# Generated by Django 2.2.6 on 2019-12-20 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('sex', models.CharField(max_length=225)),
                ('age', models.PositiveIntegerField()),
                ('phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('surgery_history', models.TextField()),
                ('surgery_history_html', models.TextField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'surgery_history')},
            },
        ),
    ]
