# Generated by Django 2.2.6 on 2019-12-20 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_choice', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LowThyroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Option')),
            ],
        ),
        migrations.CreateModel(
            name='LowCortisol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Option')),
            ],
        ),
        migrations.CreateModel(
            name='LowAndrogen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Option')),
            ],
        ),
        migrations.CreateModel(
            name='HighInsulin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Option')),
            ],
        ),
        migrations.CreateModel(
            name='HighCortisol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Option')),
            ],
        ),
        migrations.CreateModel(
            name='HighAndrogen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Option')),
            ],
        ),
        migrations.CreateModel(
            name='EstrogenPregnancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Option')),
            ],
        ),
        migrations.CreateModel(
            name='EstrogenDominance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Option')),
            ],
        ),
    ]
